/* Copyright 2025-2026 Eugene Petrenko (mcp@jonnyzzz.com); Copyright 2025-2026 JetBrains. Use of this source code is governed by the Apache 2.0 license. */
package com.jonnyzzz.mcpSteroid.proxy

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

/**
 * Asserts the `proxy-version.txt` classpath resource that `loadProxyVersion()` reads
 * is actually generated by the build and carries the project version — not the
 * `"0.1.0"` fallback the function falls back to when the resource is missing.
 *
 * The Gradle counterpart is `generateProxyVersionResource` in `npx-kt/build.gradle.kts`.
 * Pairing the codegen with this test keeps `loadProxyVersion()` honest the way
 * `:ij-plugin`'s `patchPluginXml` keeps the IDE plugin's `<version>` honest.
 */
class ProxyVersionResourceTest {

    @Test
    fun `proxy-version_txt is present on the classpath`() {
        val stream = ProxyVersionResourceTest::class.java.classLoader.getResourceAsStream("proxy-version.txt")
        assertNotNull(stream, "Expected proxy-version.txt to be packaged by generateProxyVersionResource")
        stream!!.close()
    }

    @Test
    fun `loadProxyVersion returns the generated value, not the fallback`() {
        val version = loadProxyVersion()
        assertTrue(version.isNotBlank(), "version must be non-blank, got: '$version'")
        // The hard-coded fallback in `loadProxyVersion()` is "0.1.0"; the generator
        // writes `project.version`. If we see "0.1.0" the resource didn't land.
        assertTrue(
            version != "0.1.0",
            "loadProxyVersion() returned the fallback '0.1.0' — generateProxyVersionResource " +
                "didn't run or its output isn't on the test classpath."
        )
    }

    @Test
    fun `version matches project_version system property when provided by the build`() {
        // Gradle's test task can pass `-PproxyVersion=<v>` as a system property so the
        // build can assert the runtime value end-to-end. The check is opt-in: when the
        // property isn't set we still validate that the resource exists (other tests).
        val expected = System.getProperty("npx-kt.expected.version") ?: return
        assertEquals(expected, loadProxyVersion())
    }
}
